### ISSUE TITLE
Search User 

### ISSUE THREAD

**Issue by PrasanBora** [PrasanBora/Linkedin_clone#1]
I am currently working on the user search implementation for a LinkedIn clone project using the MERN stack (MongoDB, Express.js, React, Node.js) 
The feature involves implementing the search functionality where users can search for other users based on their names, skills, or job titles.

Feel free to reach out in the comments for further discussion or clarifications. I am open to suggestions and would love to collaborate!

**Comment by lakshita10341** [comment]
i would like to work on it. please assign it to me

**Comment by PrasanBora** [comment]
> i would like to work on it. please assign it to me

Thank you for your attention to the issue I raised 
I would appreciate it if you could provide more detailed information on how you would implement the suggested functionality

Additionally, it would be helpful if you could show me the output resulting from the changes you are proposing

**Comment by PrasanBora** [comment]
@lakshita10341 let me known if u have any suggestions too
