### ISSUE TITLE
JavaScript implementation for LinkedIn-style post functionality including creating posts, deleting posts, liking, and commenting features.

### ISSUE THREAD

**Issue by Trishashetty11** [PrasanBora/Linkedin_clone#2]
Key features:

Users can only delete their own posts
Users can only delete their own comments
Likes are unique per user (can't like twice)
Each post and comment has timestamps
Comments can be tracked back to their authors

**Comment by Trishashetty11** [comment]
@PrasanBora Please assign me this issue and put as hackoctober fest accepted.

**Comment by PrasanBora** [comment]
@Trishashetty11 
Users can only delete their own posts this feature already implemented
Likes are unique per user (can't like twice) this feature already implemented
Each post and comment has timestamps this feature already implemented
**work on** 
Users can only delete their own comments or any other comment on his post 
Comments can be tracked back to their authors add link to the user profile name /image 
Also work on main issue of searching the user in db
